### DISCUSSION TITLE
Manage discharge block for the battery via the integration

### DISCUSSION THREAD

**Discussion by guidau** [torbennehmer/hacs-e3dc#186] [Ideas]
Hello Torben,
many thanks for the great E3DC integration !!!
Is it possible to set a discharge block for the battery via the integration?
I also have an E3DC S21X home power station and am currently asking myself whether it is possible, for example, if the sun is no longer shining and I have charged my battery via my dynamic tariff, but at some times it is still cheaper to draw the electricity directly from the grid and not to discharge the battery with losses first. Is there a setting here, i.e. if no electricity can be generated via solar, the battery should not be drained. For example, if the dynamic current is at 15 ct for 3 hours and the battery is full, it makes no sense to discharge the battery with losses, but only to draw power directly from the grid. Later, when the grid electricity is more expensive again, the battery is discharged again.

**Comment by torbennehmer** [comment]
As written in the forum :) try this:

You may want to use the actions/services to set power limits, as described in the README.md. With them, you can block E3DC from discharging (or even charging, if you’d want that). I am using this approach to prevent E3DC discharging the battery when I’m using cheap grid power from Tibber to charge my car, basically looking something like this (YAML mode, for easier transportation into the forum):

```yaml
alias: "Wallbox aktiv: S10 Entladung sperren"
description: ""
trigger:
  - type: power
    platform: device
    device_id: 5410...
    entity_id: f8da...
    domain: sensor
    above: 3.8
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - service: e3dc_rscp.set_power_limits
    data:
      device_id: b004...
      max_discharge: 0
mode: single
```

To clear the limits again, there is another action to clear the limits, basically:

```yaml
  - service: e3dc_rscp.clear_power_limits
    data:
      device_id: b004...
```

Using this approach, you can do just about anything except charging the battery from the grid (manual charging does this, but handle with care, again, check README.md for details).

Hope, this solves your problem :)
