### ISSUE TITLE
Disabling Power Limits

### ISSUE THREAD

**Issue by goebelmeier** [torbennehmer/hacs-e3dc#18]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm able to define power limits using the respective service, but i don't know how to disable power limits.

Enabling power limits works like
```
service: e3dc_rscp.set_power_limits
data:
  device_id: S10-1234567890
  max_discharge: 0
```

Trying to replicate the python-e3dc behaviour in https://github.com/fsantini/python-e3dc/blob/85762f2d9f272c706487c75efca75b0403c90e74/e3dc/_e3dc.py#L1911 i tried:
```
service: e3dc_rscp.set_power_limits
data:
  device_id: S10-1234567890
  max_discharge: None
```
but this results in **Fehler beim Aufrufen des Diensts e3dc_rscp.set_power_limits. expected int for dictionary value @ data['max_discharge']. Got None**

Any ideas or do you need to expand the service?

P.S.: Thank you so much for release 2.0. It works like a charm

### Describe the solution you'd like

Not sure if i'm the problem or the functionality is missing :-)

### Describe alternatives you've considered

Resetting the limit to the highest value results in the same behaviour, but the binary_sensor `s10e_power_limits` stays enabled

```
service: e3dc_rscp.set_power_limits
data:
  device_id: S10-1234567890
  max_discharge: 3000
```

### Additional context

./.
