### ISSUE TITLE
e3dc_service: set_power_limits: Issue "Unkown device" and "Device ... is no E3DC"

### ISSUE THREAD

**Issue by svlsbrg** [torbennehmer/hacs-e3dc#52]
## System Information

version | core-2023.9.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.21-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.32.1
Stage | running
Available Repositories | 1280
Downloaded Repositories | 9

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.08.3
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 116.5 GB
disk_used | 16.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.3.1), Terminal & SSH (9.7.1), HassOS SSH port 22222 Configurator (0.9.1a), RaspberryMatic CCU (3.71.12.20230826), Samba share (10.0.2), Studio Code Server (5.10.1), File editor (5.6.0), Advanced SSH & Web Terminal (15.0.7), Let's Encrypt (4.12.9), NGINX Home Assistant SSL proxy (3.5.0), Samba Backup (5.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 12
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 0.1.15
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 7. September 2023 um 10:51
-- | --
current_recorder_run | 7. September 2023 um 12:59
estimated_db_size | 1547.18 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I updated the integration after a few month and removed and re-added the device afterwards. Nevertheless the service for setting power limits is not working.

### Reproduction steps

Execute the service to set limits

### Debug logs

```text
e3dc_service: If at step 1: Error executing script. Error for call_service at pos 1: set_power_limits: Unkown device ID S10-....
e3dc_service: Error executing script. Error for if at pos 1: set_power_limits: Unkown device ID S10-...

websocket_api script: Error executing script. Error for call_service at pos 1: set_power_limits: Device f50f248ad0df2249c0fef02aca790505 is no E3DC.
```

**Comment by torbennehmer** [comment]
How do you call the service? I've changed the device selection at some point in the past, is this a automation script from an early version of the integration?

**Comment by svlsbrg** [comment]
Hi Torben, 

it doesn't matter if I call the service manually or by automation. 

here the automation script, which I am using. It uses precalculated limits by templates:
```
alias: e3dc_service
description: ""
trigger:
  - platform: time_pattern
    minutes: /1
condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.e3dc_auto
        state: "on"
    then:
      - service: e3dc_rscp.set_power_limits
        data:
          device_id: S10-.......
          max_charge: "{{(states('sensor.ladeleistung_opt'))|int}}"
          max_discharge: "{{(states('sensor.entladeleistung_opt'))|int}}"
    else:
      - service: e3dc_rscp.set_power_limits
        data:
          device_id: S10-.......
          max_charge: 4000
          max_discharge: 4500
mode: single

```
or direct:
<img width="1226" alt="Bildschirmfoto 2023-09-15 um 20 02 19" src="https://github.com/torbennehmer/hacs-e3dc/assets/68192191/54583c4a-619f-49b4-9932-cce86157fc17">
```
service: e3dc_rscp.set_power_limits
data:
  device_id: f50f248ad0df2249c0fef02aca790505
  max_charge: 4000
  max_discharge: 4000
```

BR

Rene

**Comment by torbennehmer** [comment]
Can you please check what the dropdown of E3DC device ID shows if you open it?

**Comment by svlsbrg** [comment]
Hi Torben, 

The drop down shows the correct device:

![image](https://github.com/torbennehmer/hacs-e3dc/assets/68192191/909816dd-47dd-43b7-b630-e5ee2fca8cc8)

Is it possible, that the device id cache selects a old e3dc device? I removed and re-added the device a few times in the past during updates. 

BR
Rene

**Comment by torbennehmer** [comment]
Hi Rene,
that looks like an old config entry to me. In the early prototype days, the device identified itself by the serial number. I changed this, as the integration is not capable of multi-point connections (you need one integration per E3DC for authorization purposes). At one point I decided not to support multiple E3DCs in one HA installation and simplified a bit of code. This lead to a new device ID, usually "E3DC" or something like that.
My suspicion is, that your E3DC config was created by one of the original setups. Please do one thing. Drop your E3DC from HA and readd it. Just to be on the safe side (call it a hunch) I'd probably fully restart E3DC in between.
That should give you an device ID like "S10E", depending on the model of the unit, which in turn should fix the problem.
Cheers, Torben

**Comment by svlsbrg** [comment]
Hi Torben, 

the reboot after deleting the device was successful. Nevertheless the device id is a very long hash, which I could only identify by switching the service within the development tools to YAML-Mode after selecting the device: f50f248ad0df2249c0fef02aca790505

The automation is working as well, if I use the long hash as device id:
```
service: e3dc_rscp.set_power_limits
data:
  device_id: f50f248ad0df2249c0fef02aca790505
  max_charge: "{{(states('sensor.ladeleistung_opt'))|int}}"
  max_discharge: "{{(states('sensor.entladeleistung_opt'))|int}}"

```

I assumed the device ID could be easier to discover e.g. "S10-722046003..."

Now it is working again. Thank you so much for your support.

BR

Rene
