### ISSUE TITLE
Total wallbox usage missing

### ISSUE THREAD

**Issue by derhappy** [torbennehmer/hacs-e3dc#90]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

There is an entity for wallbox consumption (kW), but the entity for the total consumption (kWh) is missing. 

This is the only entity missing for me to switch from my previous e3dc interface to this integration. There is also more detailed data available (kWh solar / net), but for me the sum is already enough.

### Describe the solution you'd like

A new entity for wallbox_consumption_total (or _today) is available.

### Describe alternatives you've considered

A Riemann integral would technically be possible. 
Using another interface to get the data like before would be the another valid option.

### Additional context

Currently I'm using the go-rscp command line utility by @spali (https://github.com/spali/go-rscp/). I can get the wallbox data with these keys:

```[
  [ # day current
    "DB_REQ_HISTORY_DATA_DAY",
    [
      ["DB_REQ_HISTORY_TIME_START", some nonsense ],
      ["DB_REQ_HISTORY_TIME_INTERVAL", more nonsense ],
      ["DB_REQ_HISTORY_TIME_SPAN", guess ]
    ]
  ],
  [
    "WB_REQ_DATA",
    [
      ["WB_INDEX", 0],
      "WB_REQ_ENERGY_ALL",
      "WB_REQ_ENERGY_SOLAR"
    ]
  ]
]
```

example result
```
result:
  DB_SUM_CONTAINER:
    DB_GRAPH_INDEX: -1
    DB_BAT_POWER_IN: 799.5
    DB_BAT_POWER_OUT: 731.5
    DB_DC_POWER: 4714
    DB_GRID_POWER_IN: 57
    DB_GRID_POWER_OUT: 57612
    DB_CONSUMPTION: 63710
    DB_PM_0_POWER: 0
    DB_PM_1_POWER: -1874.5
    DB_BAT_CHARGE_LEVEL: 17.696
    DB_BAT_CYCLE_COUNT: 0
    DB_CONSUMED_PRODUCTION: 99.07392
    DB_AUTARKY: 9.571495
  WB_INDEX: 0
  WB_ENERGY_ALL: 60670
  WB_ENERGY_SOLAR: 599
friendly_name: e3dc_today
```

### Diagnostics dump

[e3dc_dump.json](https://github.com/torbennehmer/hacs-e3dc/files/13462430/e3dc_dump.json)
